// Per-document "rendered page" text for ChunkViewerModal — this prototype has no real file
// storage or PDF rendering pipeline, so each seeded demo document's pages are hand-authored here,
// keyed by its `knowledgeDocumentStore` id. A source with no entry falls back to DEFAULT_PAGES (a
// generic short filler) — used for the many seeded documents outside the small set that need to
// look genuinely dense so the chunk editor (bounding-box overlay, resize, multi-chunk-per-page,
// page-fill scaling) can actually be exercised and evaluated, not just "look fine" on an
// near-empty page that has nothing to stress those features.
//
// Both DocumentPreviewPane (renders them) and knowledgeChunkStore (derives chunk content from a
// region of a page, for seeding and resize) need this list, so it lives in its own module rather
// than one importing the other's file inappropriately.
const DEFAULT_PAGES: string[] = [
  "Chính sách này áp dụng cho toàn bộ khiếu nại liên quan đến sản phẩm, dịch vụ của ngân hàng ABC. Mọi khách hàng đều có quyền gửi khiếu nại qua các kênh chính thức của ngân hàng.",
  "Khiếu nại được tiếp nhận trong vòng 24 giờ qua tổng đài, ứng dụng hoặc tại quầy giao dịch. Nhân viên tiếp nhận có trách nhiệm ghi nhận đầy đủ thông tin và mã số theo dõi.",
  "Ngân hàng cam kết phản hồi kết quả xử lý khiếu nại trong tối đa 15 ngày làm việc. Trường hợp phức tạp có thể kéo dài nhưng không quá 30 ngày, khách hàng sẽ được thông báo.",
  "Khách hàng không đồng ý với kết quả xử lý có quyền khiếu nại lần hai lên bộ phận giám sát chất lượng, hoặc phản ánh tới Ngân hàng Nhà nước theo quy định hiện hành.",
];

/** Dense, on-topic page content for the seeded demo documents that need to stress-test the
 * chunk editor — several full paragraphs per page, similar density to a real policy/contract/
 * FAQ document, keyed by the document's id in `knowledgeDocumentStore`. */
const DOCUMENT_PAGES: Record<string, string[]> = {
  // "Chính sách khiếu nại.docx" (kb-1) — expanded complaint-handling policy, 4 pages.
  "doc-1-2": [
    "Chính sách khiếu nại này áp dụng cho toàn bộ khiếu nại liên quan đến sản phẩm, dịch vụ và quy trình giao dịch của Ngân hàng ABC, bao gồm sản phẩm tiền gửi, tín dụng, thẻ, thanh toán và các dịch vụ ngân hàng điện tử. Chính sách áp dụng thống nhất cho mọi khách hàng cá nhân và khách hàng doanh nghiệp, không phân biệt kênh giao dịch hay địa điểm chi nhánh.\n\nMọi khách hàng đều có quyền gửi khiếu nại miễn phí qua các kênh chính thức của ngân hàng và được đảm bảo xử lý công bằng, minh bạch, đúng thời hạn. Ngân hàng cam kết không thu bất kỳ khoản phí nào đối với việc tiếp nhận và xử lý khiếu nại, trừ trường hợp khiếu nại được xác định là không có căn cứ và gây thiệt hại thực tế cho ngân hàng.\n\nNguyên tắc xử lý khiếu nại của ngân hàng bao gồm tôn trọng quyền lợi hợp pháp của khách hàng, xử lý khách quan dựa trên hồ sơ và chứng từ giao dịch thực tế, bảo mật thông tin cá nhân trong suốt quá trình xử lý, và thông báo kết quả bằng văn bản hoặc qua kênh khách hàng đã đăng ký. Trường hợp khiếu nại liên quan đến nhiều bộ phận, ngân hàng sẽ chỉ định một đầu mối duy nhất để theo dõi xuyên suốt.\n\nKhiếu nại được phân loại theo ba mức độ ưu tiên là khẩn cấp khi liên quan đến gian lận hoặc mất tiền, quan trọng khi liên quan đến lỗi giao dịch hoặc sai sót số dư, và thông thường khi liên quan đến chất lượng dịch vụ hoặc thái độ phục vụ. Mức độ ưu tiên quyết định thời gian phản hồi và cấp phê duyệt xử lý tương ứng.\n\nNhân viên ngân hàng tại mọi điểm giao dịch đều có trách nhiệm tiếp nhận khiếu nại ngay khi khách hàng phản ánh, không được từ chối hoặc yêu cầu khách hàng tự liên hệ kênh khác trừ khi khiếu nại vượt thẩm quyền xử lý tại chỗ.",
    "Khách hàng có thể gửi khiếu nại qua bốn kênh chính thức là tổng đài chăm sóc khách hàng hoạt động 24/7, ứng dụng ngân hàng số, quầy giao dịch tại chi nhánh, và email chăm sóc khách hàng. Mỗi kênh đều có quy trình tiếp nhận riêng nhưng đảm bảo cùng một tiêu chuẩn xử lý và thời hạn phản hồi.\n\nKhi tiếp nhận khiếu nại, nhân viên có trách nhiệm ghi nhận đầy đủ thông tin khách hàng, mô tả chi tiết sự việc, thời gian phát sinh, số tiền hoặc giao dịch liên quan, và cấp ngay một mã số theo dõi khiếu nại cho khách hàng. Mã số này giúp khách hàng tra cứu tiến độ xử lý bất kỳ lúc nào qua tổng đài hoặc ứng dụng.\n\nKhiếu nại được tiếp nhận và ghi nhận vào hệ thống trong vòng 24 giờ kể từ thời điểm khách hàng phản ánh, kể cả ngày nghỉ và ngày lễ. Đối với khiếu nại khẩn cấp liên quan đến nghi ngờ gian lận hoặc mất tiền trong tài khoản, ngân hàng sẽ tạm khóa giao dịch nghi vấn ngay khi có yêu cầu để hạn chế rủi ro phát sinh thêm.\n\nSau khi tiếp nhận, khiếu nại được chuyển tới bộ phận chuyên trách phù hợp dựa trên loại sản phẩm hoặc dịch vụ liên quan. Bộ phận này có trách nhiệm xác minh thông tin, đối chiếu chứng từ giao dịch và liên hệ lại khách hàng nếu cần bổ sung hồ sơ trong vòng 48 giờ.\n\nTrường hợp khiếu nại thiếu thông tin hoặc chứng từ cần thiết, nhân viên tiếp nhận phải hướng dẫn khách hàng bổ sung ngay tại thời điểm tiếp nhận, tránh việc khách hàng phải liên hệ lại nhiều lần.",
    "Ngân hàng cam kết phản hồi kết quả xử lý khiếu nại trong tối đa 15 ngày làm việc kể từ ngày tiếp nhận đầy đủ hồ sơ. Đối với khiếu nại phức tạp cần xác minh với bên thứ ba như tổ chức thẻ quốc tế hoặc đối tác thanh toán, thời gian xử lý có thể kéo dài nhưng không quá 30 ngày làm việc, và khách hàng phải được thông báo rõ lý do gia hạn.\n\nKhiếu nại được phân loại khẩn cấp phải được phản hồi sơ bộ trong vòng 24 giờ và có kết quả xử lý cuối cùng trong vòng 5 ngày làm việc. Khiếu nại mức độ quan trọng được xử lý trong vòng 10 ngày làm việc, còn khiếu nại thông thường được xử lý trong vòng 15 ngày làm việc theo cam kết chung của chính sách.\n\nTrách nhiệm xử lý khiếu nại được phân chia rõ ràng giữa các bộ phận, trong đó chi nhánh và tổng đài chịu trách nhiệm tiếp nhận và xử lý bước đầu, bộ phận nghiệp vụ liên quan chịu trách nhiệm xác minh chuyên môn, và bộ phận giám sát chất lượng chịu trách nhiệm giám sát tiến độ và đảm bảo tuân thủ thời hạn cam kết.\n\nTrong suốt quá trình xử lý, khách hàng được thông báo tiến độ ít nhất một lần mỗi 5 ngày làm việc nếu khiếu nại chưa có kết quả cuối cùng. Việc chậm trễ thông báo tiến độ mà không có lý do chính đáng được coi là vi phạm chính sách nội bộ và sẽ bị nhắc nhở, xử lý theo quy định nhân sự.\n\nKết quả xử lý khiếu nại phải được lập thành văn bản, nêu rõ căn cứ xử lý, kết luận và hướng giải quyết cụ thể, gửi tới khách hàng qua kênh mà khách hàng đã đăng ký nhận thông báo.",
    "Toàn bộ thông tin cá nhân và nội dung khiếu nại của khách hàng được bảo mật tuyệt đối trong suốt quá trình tiếp nhận, xác minh và lưu trữ, chỉ được chia sẻ nội bộ cho các bộ phận trực tiếp xử lý và không được cung cấp cho bên thứ ba nếu không có sự đồng ý của khách hàng hoặc yêu cầu của cơ quan có thẩm quyền.\n\nTrường hợp khiếu nại được xác định là lỗi thuộc về ngân hàng, khách hàng sẽ được hoàn trả đầy đủ số tiền bị ảnh hưởng cùng với khoản bồi thường tương ứng theo quy định nội bộ, thường được thực hiện trong vòng 3 ngày làm việc kể từ khi có kết luận chính thức. Mức bồi thường cụ thể được xác định dựa trên mức độ thiệt hại thực tế và thời gian khách hàng bị ảnh hưởng.\n\nKhách hàng không đồng ý với kết quả xử lý lần đầu có quyền khiếu nại lần hai bằng văn bản gửi lên bộ phận giám sát chất lượng trong vòng 30 ngày kể từ ngày nhận thông báo kết quả. Khiếu nại lần hai sẽ được một hội đồng độc lập với bộ phận xử lý ban đầu xem xét lại toàn bộ hồ sơ.\n\nNếu vẫn không đồng ý với kết quả xử lý lần hai, khách hàng có quyền phản ánh tới Ngân hàng Nhà nước hoặc khởi kiện ra tòa án có thẩm quyền theo quy định của pháp luật hiện hành. Ngân hàng có trách nhiệm cung cấp đầy đủ hồ sơ liên quan khi có yêu cầu từ cơ quan quản lý.\n\nMột số trường hợp ngoại lệ không thuộc phạm vi giải quyết theo chính sách này bao gồm tranh chấp phát sinh từ lỗi thao tác của chính khách hàng đã được xác nhận qua camera hoặc nhật ký hệ thống, và các khiếu nại đã có bản án hoặc quyết định có hiệu lực pháp luật. Mọi thắc mắc thêm về chính sách này, khách hàng vui lòng liên hệ tổng đài chăm sóc khách hàng hoặc bộ phận giám sát chất lượng của ngân hàng để được hỗ trợ.",
  ],
  // "Biểu lãi suất tiết kiệm 2026.pdf" (kb-1) — interest-rate schedule, 7 pages of descriptive
  // clauses (no real table rendering in this prototype).
  "doc-1-1": [
    "Biểu lãi suất tiết kiệm năm 2026 của Ngân hàng ABC áp dụng cho toàn bộ sản phẩm tiền gửi tiết kiệm dành cho khách hàng cá nhân, bao gồm hình thức gửi tại quầy và gửi trực tuyến qua ứng dụng ngân hàng số. Biểu lãi suất được cập nhật định kỳ và có hiệu lực kể từ ngày ban hành cho đến khi có thông báo điều chỉnh mới.\n\nĐối với tiền gửi không kỳ hạn, lãi suất áp dụng là 0,2%/năm, tính trên số dư thực tế cuối mỗi ngày và trả lãi vào ngày cuối cùng của tháng. Khách hàng có thể rút toàn bộ hoặc một phần số dư bất kỳ lúc nào mà không mất lãi đã phát sinh.\n\nKỳ hạn 1 tháng áp dụng lãi suất 3,0%/năm, kỳ hạn 2 tháng áp dụng lãi suất 3,2%/năm, và kỳ hạn 3 tháng áp dụng lãi suất 3,5%/năm. Đây là các kỳ hạn ngắn phù hợp với khách hàng có nhu cầu gửi tiền linh hoạt trong thời gian ngắn mà vẫn hưởng lãi suất ưu đãi hơn tiền gửi không kỳ hạn.\n\nLãi suất các kỳ hạn ngắn được tính theo phương pháp tích số ngày thực tế và áp dụng thống nhất cho mọi mức tiền gửi từ 1 triệu đồng trở lên, không phân biệt khách hàng gửi lần đầu hay tái tục sổ tiết kiệm. Khách hàng gửi từ 500 triệu đồng trở lên tại các kỳ hạn này được cộng thêm 0,1 điểm phần trăm lãi suất theo chính sách khách hàng ưu tiên.\n\nViệc thay đổi lãi suất kỳ hạn ngắn được ngân hàng thông báo công khai tại quầy giao dịch và trên ứng dụng ít nhất 3 ngày làm việc trước khi áp dụng, không ảnh hưởng đến các sổ tiết kiệm đã gửi trước đó cho đến ngày đáo hạn.",
    "Kỳ hạn 6 tháng áp dụng lãi suất 4,8%/năm, đây là một trong những kỳ hạn được khách hàng lựa chọn nhiều nhất do cân bằng tốt giữa tính thanh khoản và mức lãi suất nhận được. Lãi suất được giữ cố định trong suốt kỳ hạn gửi, không thay đổi theo biến động thị trường.\n\nKỳ hạn 7 tháng áp dụng lãi suất 4,9%/năm và kỳ hạn 8 tháng áp dụng lãi suất 5,0%/năm, phù hợp với khách hàng có kế hoạch sử dụng tiền vào các mốc thời gian cụ thể trong năm. Hai kỳ hạn này thường được khách hàng doanh nghiệp nhỏ lựa chọn để đồng bộ với chu kỳ dòng tiền kinh doanh.\n\nKỳ hạn 9 tháng áp dụng lãi suất 5,2%/năm, cao hơn đáng kể so với các kỳ hạn ngắn hơn do cam kết gửi tiền dài hơn giúp ngân hàng chủ động hơn trong kế hoạch sử dụng vốn. Khách hàng gửi kỳ hạn này được ưu tiên xét duyệt hạn mức thẻ tín dụng nếu có nhu cầu trong tương lai.\n\nĐối với nhóm kỳ hạn 6 đến 9 tháng, khách hàng có thể chọn hình thức trả lãi cuối kỳ hoặc trả lãi hàng tháng với mức lãi suất trả lãi hàng tháng thấp hơn 0,1 điểm phần trăm so với trả lãi cuối kỳ. Việc lựa chọn hình thức trả lãi được xác định ngay tại thời điểm mở sổ và không thể thay đổi trong suốt kỳ hạn.\n\nKhách hàng tái tục sổ tiết kiệm ở nhóm kỳ hạn này được áp dụng lãi suất niêm yết tại thời điểm tái tục, không giữ nguyên lãi suất cũ trừ khi có chương trình ưu đãi riêng đang áp dụng.",
    "Kỳ hạn 12 tháng là kỳ hạn phổ biến nhất trong biểu lãi suất, áp dụng mức lãi suất 5,6%/năm cho khách hàng gửi tại quầy. Đây là mốc kỳ hạn được nhiều khách hàng lựa chọn để cân đối giữa kế hoạch tài chính cá nhân và mục tiêu tối ưu lợi nhuận từ tiền nhàn rỗi.\n\nKỳ hạn 13 tháng áp dụng lãi suất 5,65%/năm và kỳ hạn 15 tháng áp dụng lãi suất 5,7%/năm, thường đi kèm các chương trình khuyến mãi tặng quà hoặc cộng thêm lãi suất vào các dịp đặc biệt trong năm. Khách hàng nên theo dõi thông báo khuyến mãi trên ứng dụng để tận dụng các ưu đãi này.\n\nKỳ hạn 18 tháng áp dụng lãi suất 5,8%/năm, phù hợp với khách hàng có kế hoạch tài chính trung hạn và không có nhu cầu sử dụng tiền trong ngắn hạn. Mức lãi suất này được giữ cố định trong toàn bộ 18 tháng kể từ ngày gửi.\n\nNhóm kỳ hạn từ 12 đến 18 tháng được hưởng thêm quyền lợi cầm cố sổ tiết kiệm để vay vốn tại ngân hàng với lãi suất vay ưu đãi, tối đa bằng 90% giá trị sổ tiết kiệm. Đây là quyền lợi giúp khách hàng vẫn có thể tiếp cận nguồn vốn khi cần mà không phải tất toán trước hạn.\n\nĐối với khách hàng doanh nghiệp gửi kỳ hạn từ 12 tháng trở lên với số tiền từ 5 tỷ đồng, ngân hàng áp dụng cơ chế thỏa thuận lãi suất riêng dựa trên tổng quan hệ giao dịch, có thể cao hơn biểu lãi suất niêm yết công khai.",
    "Kỳ hạn 24 tháng áp dụng lãi suất 5,9%/năm và kỳ hạn 36 tháng áp dụng lãi suất 6,0%/năm, đây là hai kỳ hạn dài nhất trong biểu lãi suất tiêu chuẩn, dành cho khách hàng có mục tiêu tích lũy dài hạn như quỹ hưu trí hoặc quỹ giáo dục cho con cái.\n\nKhách hàng gửi tiết kiệm qua ứng dụng ngân hàng số được cộng thêm 0,2 điểm phần trăm lãi suất so với biểu lãi suất gửi tại quầy ở tất cả các kỳ hạn, áp dụng như một chính sách khuyến khích giao dịch trên kênh số nhằm giảm tải cho quầy giao dịch truyền thống.\n\nViệc mở sổ tiết kiệm online yêu cầu khách hàng đã có tài khoản thanh toán và hoàn tất xác thực sinh trắc học trên ứng dụng. Số tiền gửi được trích trực tiếp từ tài khoản thanh toán và sổ tiết kiệm điện tử được lưu trữ vĩnh viễn trên hệ thống, khách hàng không cần giữ sổ giấy.\n\nLãi suất ưu đãi cộng thêm cho kênh số chỉ áp dụng cho sổ mở mới, không áp dụng cho các sổ chuyển đổi từ hình thức gửi tại quầy sang quản lý trên ứng dụng. Khách hàng có nhu cầu chuyển đổi hình thức quản lý sổ vẫn giữ nguyên lãi suất ban đầu đã cam kết.\n\nChương trình cộng lãi suất kênh số có thể được điều chỉnh hoặc tạm dừng theo từng thời kỳ tùy vào chính sách huy động vốn của ngân hàng, và sẽ được thông báo trước ít nhất 7 ngày làm việc trên ứng dụng và trang thông tin chính thức.",
    "Mức gửi tối thiểu để mở sổ tiết kiệm tại Ngân hàng ABC là 1 triệu đồng đối với tất cả các kỳ hạn, không giới hạn mức gửi tối đa. Khách hàng có thể mở nhiều sổ tiết kiệm cùng lúc với các kỳ hạn khác nhau để đa dạng hóa kế hoạch tài chính.\n\nTrường hợp khách hàng tất toán trước hạn, toàn bộ số tiền gửi sẽ được tính lại theo lãi suất không kỳ hạn 0,2%/năm cho toàn bộ thời gian đã gửi, bất kể đã gửi được bao lâu trong kỳ hạn ban đầu. Đây là quy định áp dụng chung theo hướng dẫn của Ngân hàng Nhà nước đối với tất cả tổ chức tín dụng.\n\nKhách hàng có thể tất toán một phần sổ tiết kiệm trong một số chương trình đặc biệt, phần còn lại vẫn được hưởng nguyên lãi suất kỳ hạn ban đầu cho đến ngày đáo hạn. Chương trình tất toán một phần chỉ áp dụng cho sổ tiết kiệm mở từ 100 triệu đồng trở lên.\n\nĐến ngày đáo hạn, nếu khách hàng không đến tất toán hoặc không có yêu cầu khác, sổ tiết kiệm sẽ tự động được tái tục thêm một kỳ hạn tương ứng theo lãi suất niêm yết tại thời điểm tái tục. Khách hàng được thông báo trước 3 ngày qua tin nhắn hoặc ứng dụng về việc sổ sắp đến hạn.\n\nMọi giao dịch liên quan đến sổ tiết kiệm đều yêu cầu xác thực danh tính của chủ sở hữu hoặc người được ủy quyền hợp lệ theo quy định của ngân hàng. Sổ tiết kiệm đứng tên đồng sở hữu yêu cầu chữ ký hoặc xác thực của toàn bộ đồng sở hữu khi tất toán.",
    "Khách hàng thuộc phân khúc ưu tiên với tổng tài sản từ 2 tỷ đồng trở lên được áp dụng biểu lãi suất riêng, cao hơn biểu lãi suất tiêu chuẩn từ 0,2 đến 0,3 điểm phần trăm tùy theo kỳ hạn và tổng giá trị tài sản đang quản lý tại ngân hàng.\n\nKhách hàng ưu tiên còn được hưởng các quyền lợi đi kèm như phòng chờ riêng tại chi nhánh, chuyên viên quan hệ khách hàng hỗ trợ riêng, và miễn phí toàn bộ các loại phí giao dịch liên quan đến sổ tiết kiệm. Các quyền lợi này được xét duyệt lại định kỳ mỗi 6 tháng dựa trên tổng tài sản thực tế.\n\nNgân hàng cung cấp ba hình thức trả lãi để khách hàng lựa chọn là trả lãi cuối kỳ, trả lãi định kỳ hàng tháng, và trả lãi ngay khi gửi theo hình thức chiết khấu trước. Hình thức trả lãi ngay khi gửi áp dụng mức lãi suất thấp hơn tương ứng để phản ánh giá trị thời gian của tiền.\n\nLãi trả định kỳ hàng tháng được chuyển thẳng vào tài khoản thanh toán của khách hàng vào đúng ngày tương ứng mỗi tháng, không cộng dồn vào gốc sổ tiết kiệm. Khách hàng có thể đăng ký chuyển khoản tự động số tiền lãi này sang một tài khoản tiết kiệm khác để tối ưu vòng quay dòng tiền.\n\nViệc thay đổi hình thức trả lãi sau khi đã mở sổ chỉ được thực hiện khi tất toán và mở sổ mới, ngân hàng không hỗ trợ điều chỉnh hình thức trả lãi giữa kỳ hạn đang gửi.",
    "Theo quy định hiện hành, lãi tiền gửi tiết kiệm của cá nhân không thuộc đối tượng chịu thuế thu nhập cá nhân, do đó khách hàng được nhận trọn vẹn số tiền lãi theo biểu lãi suất công bố mà không bị khấu trừ thuế. Quy định này áp dụng cho cả tiền gửi bằng đồng Việt Nam và ngoại tệ được phép huy động.\n\nĐối với khách hàng doanh nghiệp, tiền lãi từ tiết kiệm hoặc tiền gửi có kỳ hạn được tính vào thu nhập chịu thuế thu nhập doanh nghiệp theo quy định của pháp luật thuế hiện hành, doanh nghiệp có trách nhiệm tự kê khai theo đúng quy định.\n\nBiểu lãi suất này được ban hành thay thế toàn bộ các biểu lãi suất tiết kiệm trước đó và có hiệu lực kể từ ngày công bố chính thức trên các kênh thông tin của ngân hàng. Mọi sổ tiết kiệm đã mở trước thời điểm ban hành vẫn được giữ nguyên lãi suất đã cam kết cho đến ngày đáo hạn gần nhất.\n\nNgân hàng có quyền điều chỉnh biểu lãi suất theo diễn biến thị trường và định hướng điều hành chính sách tiền tệ của Ngân hàng Nhà nước, việc điều chỉnh sẽ được công bố công khai trước khi áp dụng cho các sổ mở mới. Biểu lãi suất không hồi tố đối với các sổ đã tất toán.\n\nMọi thắc mắc liên quan đến biểu lãi suất tiết kiệm, khách hàng vui lòng liên hệ tổng đài chăm sóc khách hàng hoặc đến trực tiếp chi nhánh gần nhất để được tư vấn chi tiết theo nhu cầu tài chính cá nhân.",
  ],
  // "Kịch bản xử lý từ chối giá.pdf" (kb-5) — sales objection-handling script, 3 pages.
  "doc-5-2": [
    "Kịch bản này hướng dẫn nhân viên tư vấn cách xử lý tình huống khách hàng từ chối vì lý do giá cả trong quá trình tư vấn bán sản phẩm, dịch vụ tài chính của ngân hàng. Mục tiêu là giúp khách hàng nhìn nhận đúng giá trị sản phẩm thay vì chỉ so sánh về mức phí hoặc lãi suất đơn thuần.\n\nTừ chối vì giá thường xuất hiện dưới nhiều hình thức khác nhau như phí này cao quá, ngân hàng khác rẻ hơn, hoặc để tôi suy nghĩ thêm. Nhân viên tư vấn cần nhận diện đây là tín hiệu khách hàng đang quan tâm nhưng chưa thấy đủ giá trị, chứ không phải là một lời từ chối dứt khoát.\n\nNguyên tắc đầu tiên khi xử lý từ chối giá là lắng nghe đầy đủ mối quan tâm của khách hàng trước khi phản hồi, tuyệt đối không ngắt lời hoặc phản bác ngay lập tức. Việc phản bác vội vàng khiến khách hàng cảm thấy bị áp đặt và làm giảm thiện cảm với nhân viên tư vấn.\n\nNguyên tắc thứ hai là luôn xác nhận lại mối quan tâm của khách hàng bằng cách diễn đạt lại theo cách hiểu của mình, giúp khách hàng cảm thấy được lắng nghe và tạo không khí trao đổi cởi mở hơn trước khi đi vào phần giải thích giá trị sản phẩm.\n\nNguyên tắc thứ ba là không bao giờ hạ giá hoặc cam kết miễn phí ngoài thẩm quyền để giữ chân khách hàng, vì điều này ảnh hưởng đến uy tín và chính sách giá chung của ngân hàng. Mọi đề xuất ưu đãi phải nằm trong khung chính sách đã được phê duyệt.",
    "Tình huống khách hàng nói phí cao hơn ngân hàng khác nên được xử lý bằng cách hỏi rõ khách hàng đang so sánh với sản phẩm cụ thể nào, sau đó làm rõ sự khác biệt về quyền lợi đi kèm như bảo hiểm miễn phí, hạn mức ưu đãi, hoặc dịch vụ chăm sóc riêng mà đối thủ không có. Nhân viên nên nêu cụ thể từng quyền lợi thay vì chỉ nói chung chung là sản phẩm của mình tốt hơn.\n\nTình huống khách hàng muốn suy nghĩ thêm thường là cách từ chối gián tiếp, nhân viên nên tìm hiểu nguyên nhân thực sự bằng câu hỏi mở để khách hàng chia sẻ rõ hơn. Từ đó xác định khách hàng còn băn khoăn về giá, tính năng, hay đơn giản là chưa đủ tin tưởng vào sản phẩm.\n\nTình huống khách hàng yêu cầu giảm phí trực tiếp cần được nhân viên tư vấn giải thích rõ cơ cấu phí đã được xây dựng để đảm bảo chất lượng dịch vụ tốt nhất, đồng thời gợi ý các chương trình ưu đãi đang áp dụng như miễn phí năm đầu hoặc hoàn phí khi đạt điều kiện giao dịch. Không nên từ chối một cách cộc lốc mà cần đưa ra phương án thay thế cụ thể.\n\nTình huống khách hàng so sánh với sản phẩm miễn phí của đối thủ nên được xử lý bằng cách nhấn mạnh vào sự khác biệt về chất lượng dịch vụ, mức độ an toàn, và uy tín thương hiệu, đồng thời khéo léo chỉ ra rằng sản phẩm miễn phí thường đi kèm giới hạn về hạn mức hoặc quyền lợi bảo vệ khách hàng.",
    "Sau khi giải thích giá trị sản phẩm, nhân viên nên chủ động đề xuất bước tiếp theo thay vì chờ khách hàng tự quyết định, tạo cảm giác cấp bách hợp lý để giúp khách hàng đưa ra quyết định nhanh hơn mà không cảm thấy bị thúc ép quá mức.\n\nTrong trường hợp khách hàng vẫn kiên quyết từ chối sau khi đã được giải thích đầy đủ, nhân viên nên tôn trọng quyết định của khách hàng, cảm ơn vì đã dành thời gian trao đổi, và chủ động đề nghị giữ liên hệ để tư vấn lại khi khách hàng có nhu cầu trong tương lai. Tuyệt đối không thể hiện thái độ khó chịu hoặc thúc ép quá mức khi khách hàng từ chối.\n\nNhân viên cần ghi chú lại lý do từ chối cụ thể của khách hàng vào hệ thống quản lý quan hệ khách hàng để bộ phận chăm sóc có thể tiếp cận lại với thông tin và giải pháp phù hợp hơn ở lần liên hệ sau. Việc ghi chú đầy đủ giúp tránh lặp lại cùng một cách tiếp cận không hiệu quả.\n\nMột số lỗi cần tránh khi xử lý từ chối giá bao gồm tranh cãi trực tiếp với khách hàng về mức giá, so sánh tiêu cực về đối thủ cạnh tranh, và đưa ra cam kết vượt thẩm quyền chỉ để chốt được giao dịch. Những hành vi này có thể gây rủi ro uy tín và pháp lý cho ngân hàng về lâu dài.",
  ],
};

/** Returns the rendered pages for a given document/URL/agent-item id, falling back to the
 * generic filler for any source outside the curated set above. */
export function getPagesForSource(sourceId: string | undefined): string[] {
  return (sourceId && DOCUMENT_PAGES[sourceId]) || DEFAULT_PAGES;
}
