import { useEffect, useRef, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import {
  ArrowLeft, Sparkles, Send, Check, Loader2, Wand2, Bot, User, Wrench, BookOpen,
  Workflow, Paperclip, AtSign, Settings2, Play, Save, ArrowUpRight, Cog,
  Globe, Search, FileText, Code2, FileSpreadsheet, Clock, Hand, ChevronRight,
  Database, MessageSquareText, CheckCircle2, Rocket, Layers,
  CornerDownLeft, HelpCircle,
} from "lucide-react";
import { updateUser } from "@/lib/onboarding";
import { businessProcessStore, type BpStrategy } from "@/components/business-processes/businessProcessStore";
import { taskStore } from "@/components/tasks/taskStore";
import { knowledgeStore } from "@/components/knowledge/knowledgeStore";

function commitDraftToAgent(agentId: string, draft: { bps: { name: string; description: string; strategy: string; isDefault?: boolean; toolNames?: string[]; taskNames?: string[] }[]; tasks: { name: string; description: string }[]; knowledge: { name: string; type: "doc" | "url" | "faq"; description: string }[] }) {
  const stratMap: Record<string, BpStrategy> = {
    "ReAct": "react",
    "Predefined Plan": "predefined",
    "Tool Execution": "tool_execution",
  };
  // Create tasks first so we can resolve name → id when wiring BPs
  const existingTasks = taskStore.list(agentId);
  const taskIdByName = new Map<string, string>();
  for (const t of existingTasks) taskIdByName.set(t.name.toLowerCase(), t.id);
  for (const t of draft.tasks) {
    const key = t.name.toLowerCase();
    if (taskIdByName.has(key)) continue;
    const rec = taskStore.create(agentId, t.name, t.description);
    taskIdByName.set(key, rec.id);
  }

  const slug = (s: string) => s.toLowerCase().trim().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");

  const existingBps = businessProcessStore.list(agentId);
  for (const b of draft.bps) {
    if (b.isDefault) continue;
    if (existingBps.some(e => e.name.toLowerCase() === b.name.toLowerCase())) continue;
    const taskIds = (b.taskNames ?? [])
      .map(n => taskIdByName.get(n.toLowerCase()))
      .filter((x): x is string => !!x);
    const toolIds = (b.toolNames ?? []).map(slug);
    businessProcessStore.create(agentId, {
      name: b.name,
      description: b.description,
      goal: b.description,
      strategy: stratMap[b.strategy] ?? "react",
      instruction: `Auto-generated by Inventor. Refine this instruction to fit the ${b.name} scenario.`,
      taskIds,
      toolIds,
    });
  }
  const existingK = knowledgeStore.list(agentId);
  for (const k of draft.knowledge) {
    if (existingK.some(e => e.name.toLowerCase() === k.name.toLowerCase())) continue;
    knowledgeStore.add(agentId, { name: k.name, kind: k.type, description: k.description });
  }
}

/* ---------------- Types ---------------- */
type TodoStatus = "pending" | "running" | "done";
type Todo = { id: string; label: string; status: TodoStatus };

type ClarifyQ = { id: string; question: string; options: string[] };

type ChatMsg =
  | { id: string; role: "user"; text: string }
  | { id: string; role: "ai"; kind: "source"; label: string }
  | { id: string; role: "ai"; kind: "text"; text: string }
  | { id: string; role: "ai"; kind: "todo"; todos: Todo[]; title?: string }
  | { id: string; role: "ai"; kind: "strategy"; reportTypes: string[]; triggers: { label: string; icon: any }[] }
  | { id: string; role: "ai"; kind: "cta"; label: string; done?: boolean }
  | { id: string; role: "ai"; kind: "inventory-batch"; title: string; icon: any; items: string[] }
  | { id: string; role: "ai"; kind: "clarify"; questions: ClarifyQ[]; answers: Record<string, string>; submitted: boolean };

type Tool = { name: string; desc: string; icon: any; tint: string };
type BpDraft = { name: string; description: string; strategy: "ReAct" | "Predefined Plan" | "Tool Execution"; isDefault?: boolean; toolNames?: string[]; taskNames?: string[] };
type TaskDraft = { name: string; description: string };
type KnowledgeDraft = { name: string; type: "doc" | "url" | "faq"; description: string };

type AgentDraft = {
  name: string;
  emoji: string;
  persona: string;
  description: string;
  expertise: string[];
  bps: BpDraft[];
  tasks: TaskDraft[];
  tools: Tool[];
  knowledge: KnowledgeDraft[];
  trigger: "Manual" | "Weekly" | "Manual + Weekly";
  tone: "Professional" | "Formal" | "Friendly";
  extraSteps: string[];
};

const emptyDraft: AgentDraft = {
  name: "Untitled agent",
  emoji: "✨",
  persona: "—",
  description: "Describe what you want and Inventor will draft a full configuration.",
  expertise: [],
  bps: [],
  tasks: [],
  tools: [],
  knowledge: [],
  trigger: "Manual",
  tone: "Professional",
  extraSteps: [],
};

const reportDraft: AgentDraft = {
  name: "Report Writing Agent",
  emoji: "📝",
  persona: "Report Writing Expert",
  description:
    "A senior research analyst that gathers signals from the web, runs analysis on raw numbers, and produces publication-ready reports across business, research and engineering domains.",
  expertise: [
    "Multi-source web research & synthesis",
    "Quantitative data analysis with Python",
    "Executive-grade narrative writing",
    "Citation & source verification",
  ],
  bps: [
    { name: "others", description: "Default fallback — answer general questions from knowledge.", strategy: "ReAct", isDefault: true },
    { name: "weekly_report", description: "Generate the weekly executive report on schedule.", strategy: "Predefined Plan", toolNames: ["Google Search", "Python code", "Google Docs"] },
    { name: "research_brief", description: "Run focused research on a topic and produce a brief.", strategy: "ReAct", toolNames: ["Google Search", "Perplexity", "Firecrawl"], taskNames: ["collect_topic_brief", "synthesize_findings"] },
    { name: "publish_report", description: "Format and publish the finished report to Google Docs.", strategy: "Tool Execution", toolNames: ["Google Docs", "Google Sheets"] },
  ],
  tasks: [
    { name: "collect_topic_brief", description: "Ask the user for scope, audience and required depth." },
    { name: "synthesize_findings", description: "Cluster sources, extract insights and draft sections." },
  ],
  tools: [
    { name: "Google Search", desc: "Surface authoritative web sources.", icon: Search, tint: "bg-info/15 text-info" },
    { name: "Perplexity", desc: "Deep-research with grounded citations.", icon: Sparkles, tint: "bg-primary-soft text-primary" },
    { name: "Firecrawl", desc: "Scrape pages into clean structured text.", icon: Globe, tint: "bg-accent-soft text-accent" },
    { name: "Python code", desc: "Run quantitative analysis on raw data.", icon: Code2, tint: "bg-surface-muted text-foreground" },
    { name: "Google Docs", desc: "Publish the formatted report.", icon: FileText, tint: "bg-info/15 text-info" },
    { name: "Google Sheets", desc: "Export tables & supporting data.", icon: FileSpreadsheet, tint: "bg-primary-soft text-primary" },
  ],
  knowledge: [
    { name: "Report style guide", type: "doc", description: "House style, tone and formatting rules." },
    { name: "Past reports archive", type: "doc", description: "Reference patterns and prior decisions." },
  ],
  trigger: "Manual + Weekly",
  tone: "Professional",
  extraSteps: [],
};

const careDraft: AgentDraft = {
  name: "Customer Care Agent",
  emoji: "🎧",
  persona: "24/7 customer-care specialist",
  description:
    "A 24/7 customer-care agent that answers FAQs, verifies customers, handles bookings and escalates complex cases to a human advisor.",
  expertise: [
    "FAQ resolution from knowledge base",
    "Identity verification & card operations",
    "Appointment booking",
    "Empathetic escalation handoff",
  ],
  bps: [
    { name: "others", description: "Default fallback — answer general questions from knowledge.", strategy: "ReAct", isDefault: true },
    { name: "verify_customer", description: "Verify the customer by phone before any sensitive action.", strategy: "Predefined Plan", toolNames: ["verify_customer"], taskNames: ["collect_customer_info"] },
    { name: "lock_card", description: "Lock a card after identity check.", strategy: "Predefined Plan", toolNames: ["verify_customer", "lock_card"] },
    { name: "book_appointment", description: "Book a consultation slot with an advisor.", strategy: "ReAct", toolNames: ["calendar_create_event", "send_sms"], taskNames: ["confirm_booking"] },
  ],
  tasks: [
    { name: "collect_customer_info", description: "Collect phone, full name and reason for contact." },
    { name: "confirm_booking", description: "Read back the booking details and capture confirmation." },
  ],
  tools: [
    { name: "verify_customer", desc: "Verify a customer by phone or ID.", icon: User, tint: "bg-primary-soft text-primary" },
    { name: "lock_card", desc: "Lock a card via the core banking API.", icon: Wrench, tint: "bg-destructive/10 text-destructive" },
    { name: "calendar_create_event", desc: "Create a Google Calendar event.", icon: Clock, tint: "bg-info/15 text-info" },
    { name: "send_sms", desc: "Send a transactional SMS confirmation.", icon: Send, tint: "bg-accent-soft text-accent" },
  ],
  knowledge: [
    { name: "FAQ — Card policy", type: "faq", description: "Top 30 FAQs about card products & limits." },
    { name: "Booking guide", type: "doc", description: "Branch list, slots and required documents." },
  ],
  trigger: "Manual",
  tone: "Friendly",
  extraSteps: [],
};

/* ---------------- Page ---------------- */
export default function Inventor() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const seedPrompt = params.get("prompt") ?? "";
  const fromOnboarding = params.get("from") === "onboarding";

  const [messages, setMessages] = useState<ChatMsg[]>([]);
  const [input, setInput] = useState("");
  const [thinking, setThinking] = useState(false);
  const [draft, setDraft] = useState<AgentDraft>(emptyDraft);
  const [configApplied, setConfigApplied] = useState(false);
  const scrollerRef = useRef<HTMLDivElement>(null);
  const startedRef = useRef(false);

  /* auto-seed first message */
  useEffect(() => {
    if (startedRef.current) return;
    startedRef.current = true;
    if (seedPrompt.trim()) {
      runConversation(seedPrompt.trim());
    }
  }, [seedPrompt]);

  /* scroll to bottom on update */
  useEffect(() => {
    scrollerRef.current?.scrollTo({ top: scrollerRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, thinking]);

  /* ---------- chat helpers ---------- */
  const pushMsg = (m: ChatMsg) => setMessages(p => [...p, m]);
  const updateMsg = (id: string, updater: (m: ChatMsg) => ChatMsg) =>
    setMessages(p => p.map(m => (m.id === id ? updater(m) : m)));
  const wait = (ms: number) => new Promise(r => setTimeout(r, ms));

  /* ---------- the scripted "AI" flow ---------- */
  async function runConversation(userPrompt: string) {
    pushMsg({ id: crypto.randomUUID(), role: "user", text: userPrompt });
    setThinking(true);
    await wait(700);

    // Acknowledge
    pushMsg({
      id: crypto.randomUUID(),
      role: "ai",
      kind: "text",
      text: `Got it — I'll design **${guessAgentName(userPrompt)}**. Let me draft a plan first.`,
    });
    await wait(500);

    // Todo list
    const todoId = crypto.randomUUID();
    const todos: Todo[] = [
      { id: "t1", label: "Set up basic information", status: "pending" },
      { id: "t2", label: "Find suitable tools", status: "pending" },
      { id: "t3", label: "Write the System Prompt", status: "pending" },
      { id: "t4", label: "Configure triggers", status: "pending" },
    ];
    pushMsg({ id: todoId, role: "ai", kind: "todo", todos, title: "Todo List" });
    await wait(450);

    // Run each item
    for (let i = 0; i < todos.length; i++) {
      updateMsg(todoId, m => {
        if (m.role !== "ai" || m.kind !== "todo") return m;
        const next = m.todos.map((t, idx) => (idx === i ? { ...t, status: "running" as TodoStatus } : t));
        return { ...m, todos: next };
      });
      await wait(700);
      updateMsg(todoId, m => {
        if (m.role !== "ai" || m.kind !== "todo") return m;
        const next = m.todos.map((t, idx) => (idx === i ? { ...t, status: "done" as TodoStatus } : t));
        return { ...m, todos: next };
      });
      await wait(200);
    }

    // Strategy proposal
    pushMsg({
      id: crypto.randomUUID(),
      role: "ai",
      kind: "text",
      text:
        "Based on your prompt I've inferred the relevant report families and a sensible trigger schedule. Review below — you can refine anything afterwards.",
    });
    await wait(400);
    pushMsg({
      id: crypto.randomUUID(),
      role: "ai",
      kind: "strategy",
      reportTypes: ["Business reports", "Research briefs", "Technical write-ups"],
      triggers: [
        { label: "Manual run", icon: Hand },
        { label: "Weekly schedule", icon: Clock },
      ],
    });
    await wait(400);

    // CTA
    pushMsg({
      id: crypto.randomUUID(),
      role: "ai",
      kind: "cta",
      label: "Update configuration",
    });

    setThinking(false);
  }

  /* user clicks "Update configuration" */
  async function applyConfiguration(ctaId: string) {
    updateMsg(ctaId, m => (m.role === "ai" && m.kind === "cta" ? { ...m, done: true } : m));
    // Pick draft based on prompt keyword
    const prompt = (seedPrompt || "").toLowerCase();
    const target =
      prompt.includes("customer") || prompt.includes("care") || prompt.includes("cskh") || prompt.includes("faq") || prompt.includes("booking")
        ? careDraft
        : reportDraft;
    setConfigApplied(true);
    setDraft(prev => ({
      ...prev,
      name: target.name, emoji: target.emoji, persona: target.persona,
      description: target.description, trigger: target.trigger, tone: target.tone,
    }));
    setThinking(true);
    await wait(500);

    // Expertise
    pushMsg({ id: crypto.randomUUID(), role: "ai", kind: "text", text: "✅ Configuration applied. Now wiring up Core Expertise…" });
    for (const e of target.expertise) {
      await wait(220);
      setDraft(d => ({ ...d, expertise: [...d.expertise, e] }));
    }

    // Business processes
    await wait(350);
    pushMsg({
      id: crypto.randomUUID(), role: "ai", kind: "inventory-batch",
      title: "Designing business processes", icon: Layers,
      items: target.bps.map(b => b.name),
    });
    for (const b of target.bps) {
      await wait(260);
      setDraft(d => ({ ...d, bps: [...d.bps, b] }));
    }

    // Tasks
    await wait(350);
    pushMsg({
      id: crypto.randomUUID(), role: "ai", kind: "inventory-batch",
      title: "Drafting tasks", icon: Workflow,
      items: target.tasks.map(t => t.name),
    });
    for (const tk of target.tasks) {
      await wait(260);
      setDraft(d => ({ ...d, tasks: [...d.tasks, tk] }));
    }

    // Tools
    await wait(350);
    pushMsg({
      id: crypto.randomUUID(), role: "ai", kind: "inventory-batch",
      title: "Adding recommended tools", icon: Wrench,
      items: target.tools.map(t => t.name),
    });
    for (const t of target.tools) {
      await wait(260);
      setDraft(d => ({ ...d, tools: [...d.tools, t] }));
    }

    // Knowledge
    await wait(350);
    pushMsg({
      id: crypto.randomUUID(), role: "ai", kind: "inventory-batch",
      title: "Curating knowledge sources", icon: BookOpen,
      items: target.knowledge.map(k => k.name),
    });
    for (const k of target.knowledge) {
      await wait(260);
      setDraft(d => ({ ...d, knowledge: [...d.knowledge, k] }));
    }

    await wait(300);
    pushMsg({
      id: crypto.randomUUID(), role: "ai", kind: "text",
      text:
        "All set. You can keep chatting to refine — e.g. *“add a SLA business process”* or *“use a more formal tone”*.",
    });
    setThinking(false);
  }

  /* free-form follow-up after config applied */
  async function handleFollowup(text: string) {
    pushMsg({ id: crypto.randomUUID(), role: "user", text });
    setThinking(true);
    await wait(600);

    const t = text.toLowerCase();
    if (t.includes("slack")) {
      setDraft(d => ({ ...d, extraSteps: [...d.extraSteps, "Send finished report to Slack channel"] }));
      pushMsg({
        id: crypto.randomUUID(),
        role: "ai",
        kind: "text",
        text: "Added a **Slack delivery step** to the right panel — it will fire after the report is written.",
      });
    } else if (t.includes("formal") || t.includes("trang trọng")) {
      setDraft(d => ({ ...d, tone: "Formal" }));
      pushMsg({
        id: crypto.randomUUID(),
        role: "ai",
        kind: "text",
        text: "Tone switched to **Formal**. The persona prompt has been rewritten on the right.",
      });
    } else if (t.includes("weekly") || t.includes("schedule")) {
      setDraft(d => ({ ...d, trigger: "Weekly" }));
      pushMsg({ id: crypto.randomUUID(), role: "ai", kind: "text", text: "Trigger updated to **Weekly**." });
    } else {
      pushMsg({
        id: crypto.randomUUID(),
        role: "ai",
        kind: "text",
        text: "Noted — I've folded that into the configuration. Anything else?",
      });
    }
    setThinking(false);
  }

  /* submit handler */
  function onSubmit() {
    const v = input.trim();
    if (!v) return;
    setInput("");
    if (messages.length === 0) runConversation(v);
    else handleFollowup(v);
  }

  /* ---------------- Render ---------------- */
  return (
    <div className="h-screen flex flex-col bg-background">
      {/* Top bar */}
      <header className="h-14 border-b border-border bg-surface px-5 flex items-center gap-3 shrink-0">
        <button onClick={() => navigate("/")} className="h-8 w-8 rounded-lg hover:bg-surface-muted flex items-center justify-center transition-base text-muted-foreground">
          <ArrowLeft size={15} />
        </button>
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-primary to-primary-glow flex items-center justify-center text-primary-foreground">
            <Wand2 size={13} />
          </div>
          <div>
            <div className="text-sm font-semibold font-display leading-tight">Inventor</div>
            <div className="text-[10px] text-muted-foreground leading-tight">Describe → Draft → Deploy</div>
          </div>
        </div>
        <div className="ml-auto flex items-center gap-2">
          {fromOnboarding && (
            <span className="chip chip-primary text-[10px] hidden sm:inline-flex">
              <Rocket size={11} /> First agent setup
            </span>
          )}
          <button className="btn-secondary h-8 text-xs">
            <Save size={12} /> Save draft
          </button>
          <button
            disabled={!configApplied}
            onClick={() => {
              if (fromOnboarding) updateUser({ firstTime: false });
              commitDraftToAgent("cskh", draft);
              navigate(
                fromOnboarding ? "/agents/cskh?welcome=1" : "/agents/cskh",
              );
            }}
            title={
              fromOnboarding && configApplied
                ? "Happy with it? Open your agent to test and tweak."
                : undefined
            }
            className="btn-primary h-8 text-xs disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Play size={12} /> Open agent
          </button>
        </div>
      </header>

      <div className="flex-1 grid grid-cols-1 lg:grid-cols-[minmax(380px,460px)_1fr] overflow-hidden">
        {/* LEFT — Chat */}
        <aside className="border-r border-border bg-surface flex flex-col min-h-0">
          <div className="h-11 px-4 border-b border-border flex items-center gap-2 shrink-0">
            <Sparkles size={13} className="text-primary" />
            <span className="text-xs font-semibold">Inventor chat</span>
            <span className="ml-auto text-[10px] text-muted-foreground">Auto-saves</span>
          </div>

          <div ref={scrollerRef} className="flex-1 overflow-y-auto px-4 py-4 space-y-3">
            {messages.length === 0 && !seedPrompt && <Welcome />}
            {messages.map(m => (
              <MessageBubble key={m.id} msg={m} onCta={() => m.role === "ai" && m.kind === "cta" && !m.done && applyConfiguration(m.id)} />
            ))}
            {thinking && <Thinking />}
          </div>

          {/* Composer */}
          <div className="p-3 border-t border-border shrink-0">
            <div className="rounded-xl border border-border bg-background focus-within:border-primary focus-within:ring-glow transition-base p-1.5">
              <textarea
                value={input}
                onChange={e => setInput(e.target.value)}
                onKeyDown={e => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    onSubmit();
                  }
                }}
                rows={2}
                placeholder={messages.length === 0 ? "Ask Inventor to build anything..." : "Refine the agent — e.g. add Slack, change tone…"}
                className="w-full resize-none bg-transparent text-sm placeholder:text-muted-foreground outline-none px-2.5 py-2 max-h-32"
              />
              <div className="flex items-center gap-1 px-1.5 pb-0.5">
                <button className="h-7 w-7 rounded-md hover:bg-surface-muted flex items-center justify-center text-muted-foreground transition-base"><Paperclip size={12} /></button>
                <button className="h-7 w-7 rounded-md hover:bg-surface-muted flex items-center justify-center text-muted-foreground transition-base"><AtSign size={12} /></button>
                <button
                  onClick={onSubmit}
                  className="ml-auto h-7 px-3 rounded-md bg-primary text-primary-foreground hover:bg-primary-glow text-xs font-medium flex items-center gap-1.5 transition-base disabled:opacity-50"
                  disabled={!input.trim()}
                >
                  Send <Send size={10} />
                </button>
              </div>
            </div>
          </div>
        </aside>

        {/* RIGHT — Configuration */}
        <main className="flex flex-col min-h-0 overflow-y-auto bg-background">
          <ConfigPanel draft={draft} applied={configApplied} />
        </main>
      </div>
    </div>
  );
}

/* ---------------- Sub components ---------------- */

function Welcome() {
  return (
    <div className="rounded-xl border border-dashed border-border p-5 text-center bg-background/50">
      <div className="w-10 h-10 mx-auto rounded-xl bg-primary-soft text-primary flex items-center justify-center mb-2">
        <Wand2 size={16} />
      </div>
      <div className="text-sm font-semibold mb-1 font-display">Ask Inventor to build anything</div>
      <p className="text-[11px] text-muted-foreground max-w-[280px] mx-auto">
        Try: <span className="text-foreground">"Tạo Agent viết báo cáo"</span> or
        <span className="text-foreground"> "HR onboarding assistant"</span>
      </p>
    </div>
  );
}

function Thinking() {
  return (
    <div className="flex items-start gap-2.5">
      <div className="w-6 h-6 rounded-lg bg-primary-soft text-primary flex items-center justify-center shrink-0">
        <Bot size={12} />
      </div>
      <div className="rounded-2xl rounded-tl-sm bg-surface-muted px-3 py-2 flex items-center gap-1.5">
        <Loader2 size={11} className="animate-spin text-muted-foreground" />
        <span className="text-[11px] text-muted-foreground">Inventor is thinking…</span>
      </div>
    </div>
  );
}

function MessageBubble({ msg, onCta }: { msg: ChatMsg; onCta: () => void }) {
  if (msg.role === "user") {
    return (
      <div className="flex items-start gap-2.5 justify-end">
        <div className="rounded-2xl rounded-tr-sm bg-primary text-primary-foreground px-3.5 py-2 max-w-[85%] text-[13px] leading-relaxed shadow-soft">
          {msg.text}
        </div>
        <div className="w-6 h-6 rounded-lg bg-surface-muted flex items-center justify-center shrink-0">
          <User size={12} />
        </div>
      </div>
    );
  }

  return (
    <div className="flex items-start gap-2.5">
      <div className="w-6 h-6 rounded-lg bg-primary-soft text-primary flex items-center justify-center shrink-0">
        <Bot size={12} />
      </div>
      <div className="flex-1 min-w-0 space-y-2">
        {msg.kind === "text" && (
          <div className="rounded-2xl rounded-tl-sm bg-surface-muted px-3.5 py-2 text-[13px] leading-relaxed">
            <Markdownish text={msg.text} />
          </div>
        )}
        {msg.kind === "todo" && <TodoCard title={msg.title ?? "Todo List"} todos={msg.todos} />}
        {msg.kind === "strategy" && <StrategyCard reportTypes={msg.reportTypes} triggers={msg.triggers} />}
        {msg.kind === "inventory-batch" && <InventoryBatchCard title={msg.title} icon={msg.icon} items={msg.items} />}
        {msg.kind === "cta" && (
          <button
            onClick={onCta}
            disabled={msg.done}
            className={`w-full rounded-xl border px-3.5 py-2.5 flex items-center justify-between gap-2 transition-base text-left ${
              msg.done
                ? "border-primary/40 bg-primary-soft/60 cursor-default"
                : "border-primary bg-gradient-to-r from-primary to-primary-glow text-primary-foreground hover:shadow-elev"
            }`}
          >
            <div className="flex items-center gap-2">
              {msg.done ? <Check size={13} className="text-primary" /> : <Sparkles size={13} />}
              <span className="text-[13px] font-semibold">{msg.done ? "Configuration applied" : msg.label}</span>
            </div>
            {!msg.done && <ChevronRight size={14} />}
          </button>
        )}
      </div>
    </div>
  );
}

function TodoCard({ title, todos }: { title: string; todos: Todo[] }) {
  const doneCount = todos.filter(t => t.status === "done").length;
  return (
    <div className="rounded-xl border border-border bg-background overflow-hidden">
      <div className="px-3.5 py-2 border-b border-border flex items-center gap-2 bg-surface-muted/60">
        <Workflow size={12} className="text-primary" />
        <span className="text-[11px] font-semibold uppercase tracking-wider">{title}</span>
        <span className="ml-auto text-[10px] text-muted-foreground">{doneCount}/{todos.length}</span>
      </div>
      <ul className="p-1.5">
        {todos.map(t => (
          <li key={t.id} className="flex items-center gap-2 px-2 py-1.5 rounded-md hover:bg-surface-muted/40">
            <div className="w-4 h-4 rounded-full border flex items-center justify-center shrink-0 transition-base
              ${t.status === 'done' ? 'border-primary bg-primary' : 'border-border'}"
              style={{
                borderColor: t.status === "done" ? "hsl(var(--primary))" : undefined,
                background: t.status === "done" ? "hsl(var(--primary))" : undefined,
              }}
            >
              {t.status === "done" && <Check size={9} className="text-primary-foreground" />}
              {t.status === "running" && <Loader2 size={9} className="animate-spin text-primary" />}
            </div>
            <span className={`text-[12px] ${t.status === "done" ? "text-muted-foreground line-through" : "text-foreground"}`}>
              {t.label}
            </span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function StrategyCard({ reportTypes, triggers }: { reportTypes: string[]; triggers: { label: string; icon: any }[] }) {
  return (
    <div className="rounded-xl border border-border bg-background p-3 space-y-2.5">
      <div>
        <div className="text-[10px] uppercase font-semibold tracking-wider text-muted-foreground mb-1.5">Report families</div>
        <div className="flex flex-wrap gap-1.5">
          {reportTypes.map(r => (
            <span key={r} className="chip chip-primary text-[10.5px]">{r}</span>
          ))}
        </div>
      </div>
      <div>
        <div className="text-[10px] uppercase font-semibold tracking-wider text-muted-foreground mb-1.5">Triggers</div>
        <div className="flex flex-wrap gap-1.5">
          {triggers.map(t => (
            <span key={t.label} className="inline-flex items-center gap-1 px-2 py-1 rounded-md bg-surface-muted text-[11px] font-medium">
              <t.icon size={11} /> {t.label}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}

function InventoryBatchCard({ title, icon: Icon, items }: { title: string; icon: any; items: string[] }) {
  return (
    <div className="rounded-xl border border-border bg-background p-3">
      <div className="flex items-center gap-1.5 mb-2">
        <Icon size={11} className="text-primary" />
        <span className="text-[11px] font-semibold uppercase tracking-wider">{title}</span>
      </div>
      <div className="flex flex-wrap gap-1.5">
        {items.map(t => (
          <span key={t} className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-primary-soft text-primary text-[11px] font-medium">
            <CheckCircle2 size={10} /> {t}
          </span>
        ))}
      </div>
    </div>
  );
}

function Markdownish({ text }: { text: string }) {
  // Minimal **bold** + *italic*
  const parts = text.split(/(\*\*[^*]+\*\*|\*[^*]+\*)/g);
  return (
    <span>
      {parts.map((p, i) => {
        if (p.startsWith("**") && p.endsWith("**")) return <strong key={i} className="font-semibold">{p.slice(2, -2)}</strong>;
        if (p.startsWith("*") && p.endsWith("*")) return <em key={i}>{p.slice(1, -1)}</em>;
        return <span key={i}>{p}</span>;
      })}
    </span>
  );
}

/* ---------------- Right config panel ---------------- */
function ConfigPanel({ draft, applied }: { draft: AgentDraft; applied: boolean }) {
  return (
    <div className="px-8 py-7 max-w-[820px] mx-auto w-full animate-fade-up">
      {/* Header card */}
      <div className="rounded-2xl border border-border bg-surface p-5 mb-5 flex items-start gap-4 shadow-soft">
        <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-primary-soft to-accent-soft flex items-center justify-center text-3xl shrink-0">
          {draft.emoji}
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <h1 className="font-display text-xl font-semibold truncate">{draft.name}</h1>
            <span className={`chip text-[10px] ${applied ? "chip-primary" : "chip-muted"}`}>
              {applied ? "Drafted" : "Empty"}
            </span>
          </div>
          <p className="text-sm text-muted-foreground leading-relaxed">{draft.description}</p>
        </div>
      </div>

      {/* Persona */}
      <Section icon={MessageSquareText} title="Persona">
        <div className="text-sm font-semibold mb-1">{draft.persona}</div>
        <div className="text-xs text-muted-foreground">Tone: {draft.tone} · Voice tailored for {draft.persona.toLowerCase()}.</div>
      </Section>

      {/* Core expertise */}
      <Section icon={BookOpen} title="Core expertise">
        {draft.expertise.length === 0 ? (
          <EmptyHint label="No skills yet — Inventor will populate this after you approve the plan." />
        ) : (
          <ul className="grid sm:grid-cols-2 gap-1.5">
            {draft.expertise.map(e => (
              <li key={e} className="flex items-center gap-2 px-2.5 py-1.5 rounded-lg bg-surface border border-border text-[12.5px]">
                <CheckCircle2 size={12} className="text-primary shrink-0" />
                <span className="truncate">{e}</span>
              </li>
            ))}
          </ul>
        )}
      </Section>

      {/* Business processes — parents owning their tools/tasks */}
      <Section icon={Layers} title={`Business processes ${draft.bps.length ? `(${draft.bps.length})` : ""}`}>
        {draft.bps.length === 0 ? (
          <EmptyHint label="No business process drafted yet." />
        ) : (
          <ul className="space-y-2">
            {draft.bps.map(b => {
              const childTools = (b.toolNames ?? [])
                .map(n => draft.tools.find(t => t.name === n))
                .filter((t): t is Tool => !!t);
              const childTasks = (b.taskNames ?? [])
                .map(n => draft.tasks.find(t => t.name === n))
                .filter((t): t is TaskDraft => !!t);
              return (
                <li key={b.name} className="rounded-lg border border-border bg-surface overflow-hidden">
                  <div className="px-3 py-2.5 flex items-start gap-2">
                    <Layers size={12} className="text-primary mt-0.5 shrink-0" />
                    <div className="min-w-0 flex-1">
                      <div className="text-[12.5px] font-semibold flex items-center gap-1.5 flex-wrap">
                        {b.name}
                        {b.isDefault && <span className="chip chip-muted text-[9.5px]">Default</span>}
                        <span className="chip chip-primary text-[9.5px]">{b.strategy}</span>
                      </div>
                      <div className="text-[11px] text-muted-foreground leading-snug">{b.description}</div>
                    </div>
                  </div>

                  {(childTools.length > 0 || childTasks.length > 0) && (
                    <div className="bg-surface-muted/30 border-t border-border pl-6 pr-3 py-2.5 space-y-2">
                      {childTools.length > 0 && (
                        <div className="border-l-2 border-border pl-3">
                          <div className="flex items-center gap-1.5 mb-1">
                            <Wrench size={11} className="text-muted-foreground" />
                            <span className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                              Tools ({childTools.length})
                            </span>
                          </div>
                          <ul className="space-y-0.5">
                            {childTools.map(t => (
                              <li key={t.name} className="flex items-center gap-2 px-1.5 py-1 rounded-md">
                                <div className={`w-5 h-5 rounded flex items-center justify-center shrink-0 ${t.tint}`}>
                                  <t.icon size={10} />
                                </div>
                                <span className="text-[12px] font-medium truncate">{t.name}</span>
                                <span className="text-[10.5px] text-muted-foreground truncate">{t.desc}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      {childTasks.length > 0 && (
                        <div className="border-l-2 border-border pl-3">
                          <div className="flex items-center gap-1.5 mb-1">
                            <Workflow size={11} className="text-muted-foreground" />
                            <span className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                              Tasks ({childTasks.length})
                            </span>
                          </div>
                          <ul className="space-y-0.5">
                            {childTasks.map(t => (
                              <li key={t.name} className="flex items-center gap-2 px-1.5 py-1 rounded-md">
                                <CheckCircle2 size={11} className="text-primary shrink-0" />
                                <span className="text-[12px] font-medium truncate">{t.name}</span>
                                <span className="text-[10.5px] text-muted-foreground truncate">{t.description}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  )}
                </li>
              );
            })}
          </ul>
        )}

        {/* Unassigned bucket */}
        {(() => {
          const usedTools = new Set(draft.bps.flatMap(b => b.toolNames ?? []));
          const usedTasks = new Set(draft.bps.flatMap(b => b.taskNames ?? []));
          const orphanTools = draft.tools.filter(t => !usedTools.has(t.name));
          const orphanTasks = draft.tasks.filter(t => !usedTasks.has(t.name));
          if (orphanTools.length === 0 && orphanTasks.length === 0) return null;
          return (
            <div className="mt-2 rounded-lg border border-dashed border-border bg-surface/40 px-3 py-2.5">
              <div className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1.5">
                Unassigned · attach later inside the agent
              </div>
              <div className="flex flex-wrap gap-1.5">
                {orphanTools.map(t => (
                  <span key={`tool-${t.name}`} className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-surface border border-border text-[11px]">
                    <Wrench size={10} className="text-muted-foreground" /> {t.name}
                  </span>
                ))}
                {orphanTasks.map(t => (
                  <span key={`task-${t.name}`} className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-surface border border-border text-[11px]">
                    <Workflow size={10} className="text-muted-foreground" /> {t.name}
                  </span>
                ))}
              </div>
            </div>
          );
        })()}
      </Section>

      {/* Knowledge */}
      <Section icon={BookOpen} title={`Knowledge ${draft.knowledge.length ? `(${draft.knowledge.length})` : ""}`}>
        {draft.knowledge.length === 0 ? (
          <EmptyHint label="No knowledge sources curated yet." />
        ) : (
          <ul className="space-y-1.5">
            {draft.knowledge.map(k => (
              <li key={k.name} className="rounded-lg border border-border bg-surface px-3 py-2 flex items-start gap-2">
                <BookOpen size={12} className="text-primary mt-0.5 shrink-0" />
                <div className="min-w-0 flex-1">
                  <div className="text-[12.5px] font-semibold flex items-center gap-1.5">
                    {k.name}
                    <span className="chip chip-muted text-[9.5px] uppercase">{k.type}</span>
                  </div>
                  <div className="text-[11px] text-muted-foreground leading-snug truncate">{k.description}</div>
                </div>
              </li>
            ))}
          </ul>
        )}
      </Section>

      {/* Trigger */}
      <Section icon={Cog} title="Triggers">
        <div className="flex flex-wrap gap-1.5">
          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-surface border border-border text-[11.5px] font-medium">
            <Hand size={11} /> Manual
          </span>
          {draft.trigger.includes("Weekly") && (
            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-primary-soft text-primary text-[11.5px] font-semibold">
              <Clock size={11} /> Weekly schedule
            </span>
          )}
        </div>
      </Section>

      {/* Extra steps from follow-ups */}
      {draft.extraSteps.length > 0 && (
        <Section icon={Workflow} title="Workflow add-ons">
          <ul className="space-y-1.5">
            {draft.extraSteps.map(s => (
              <li key={s} className="flex items-center gap-2 px-2.5 py-1.5 rounded-lg bg-primary-soft/60 border border-primary/20 text-[12.5px]">
                <ArrowUpRight size={11} className="text-primary" />
                {s}
              </li>
            ))}
          </ul>
        </Section>
      )}

      {/* Footer hint */}
      <div className="rounded-xl border border-dashed border-border p-3 text-center text-[11px] text-muted-foreground bg-surface/40">
        Configuration updates live as you chat. When you're ready, click <span className="font-semibold text-foreground">Open agent</span> to enter the full builder.
      </div>
    </div>
  );
}

function Section({ icon: Icon, title, children }: { icon: any; title: string; children: React.ReactNode }) {
  return (
    <section className="mb-5">
      <div className="flex items-center gap-2 mb-2.5">
        <Icon size={13} className="text-primary" />
        <h3 className="text-[11px] font-semibold uppercase tracking-wider">{title}</h3>
        <div className="flex-1 h-px bg-border" />
      </div>
      {children}
    </section>
  );
}

function EmptyHint({ label }: { label: string }) {
  return (
    <div className="rounded-lg border border-dashed border-border px-3 py-2.5 text-[11.5px] text-muted-foreground bg-surface/40">
      {label}
    </div>
  );
}

/* ---------------- helpers ---------------- */
function guessAgentName(p: string) {
  const t = p.toLowerCase();
  if (t.includes("báo cáo") || t.includes("report")) return "Report Writing Agent";
  if (t.includes("hr") || t.includes("onboarding")) return "HR Onboarding Agent";
  if (t.includes("sales")) return "Sales Lead Qualifier";
  if (t.includes("support") || t.includes("customer")) return "Customer Support Agent";
  return "New Agent";
}
